db:
  url: bolt://localhost:7687
  username: neo4j
  password: banana123

nodes:
  schemata:
    Position:
      ignore: true
    Address:
      ignore: true
    Person:
      label: "Human"

  types:
    address:
      reify: true
    identifiers:
      reify: true
    phone:
      reify: true
    email:
      reify: true
    url:
      reify: true

  topics:
    labels:
      "gov.soe": "SOE"
      "gov.igo": "IGO"
      "gov.head": "HeadOfState"
      "gov.executive": "Executive"
      "gov.legislative": "Legislative"
      "gov.judicial": "Judicial"
      "gov.financial": "CentralBanking"
      "role.rca": "CloseAssociate"
      "role.pep": "Politician"
      "poi": "PersonOfInterest"
      "sanction": "Sanctioned"
      "sanction.linked": "SanctionLinked"
      "sanction.counter": "CounterSanctioned"
      "export.control": "ExportControlled"
      "export.risk": "TradeRisk"
    ignore:
      - "gov.national"
      - "gov.state"
      - "gov.muni"

edges:
  schemata:
    Occupancy:
      ignore: true
