db:
  url: bolt://localhost:7687
  username: neo4j
  password: banana123

nodes:
  schemata:
    Position:
      ignore: true
    Address:
      ignore: true
    Person:
      label: "Human"

  types:
    address:
      reify: true
    identifiers:
      reify: true
    phone:
      reify: true
    email:
      reify: true
    url:
      reify: true

  topics:
    "gov.soe":
      label: "SOE"
    "gov.igo":
      label: "IGO"
    "gov.head":
      label: "HeadOfState"
    "gov.executive":
      label: "Executive"
    "gov.legislative":
      label: "Legislative"
    "gov.judicial":
      label: "Judicial"
    "gov.financial":
      label: "CentralBanking"
    "role.rca":
      label: "CloseAssociate"
    "role.pep":
      label: "Politician"
    "poi":
      label: "PersonOfInterest"
    "sanction":
      label: "Sanctioned"
    "sanction.linked":
      label: "SanctionLinked"
    "sanction.counter":
      label: "CounterSanctioned"
    "export.control":
      label: "ExportControlled"
    "export.risk":
      label: "TradeRisk"
    "gov.national":
      ignore: true
    "gov.state":
      ignore: true
    "gov.muni":
      ignore: true

edges:
  schemata:
    Occupancy:
      ignore: true
